name: JAVA CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
       java-version: '17'
       distribution: 'temurin'
       cache: maven
    - name: Build with Maven
      run: mvn clean package
    - name: copy jar to diff folder
      run: mkdir jardir && co target/*.jar jardir
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: jardir

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
       name: Package
       path: jardir

