name: JAVA CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
       java-version: '17'
       distribution: 'temurin'
       cache: maven
    - name: Build with Maven
      run: mvn clean package
    - name: copy jar to diff folder
      run: mkdir jardir && cp target/*.jar jardir
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: jardir

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: prod
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
       name: Package
       path: jardir
    - name: Install dependencies
      run: |
        sudo apt install ansible-core
    
    - name: set ansible config secrets
      env:
        EC2_SSH_KEY: ${{ secrets.JAVA_APP_SSH_KEY }}
      run: |
        mkdir ~/.ssh
        echo "$EC2_SSH_KEY" >  ~/.ssh/ec2
        chmod 600  ~/.ssh/ec2
 
    - name: run playbook
      env:
        ANSIBLE_FORCE_COLOR: '1'
      run: |
        ansible all -m ping
        ansible-playbook deploy.yml 
      working-directory: ./deployment
